### ISSUE TITLE
Will not build for me

### ISSUE THREAD

**Issue by timmccabe** [DrBrad/Android-VPN-to-Socket#1]
I cannot get this code to build for me. The ReadMe says to modify the Proxy.java file, but there's no indication how it's supposed to be modified. Proxy.java is where all the errors are.

![Screen Shot 2020-12-21 at 4 16 39 PM](https://user-images.githubusercontent.com/56164109/102823107-3f453900-43a8-11eb-9324-d4ba38f1a0de.png)

**Comment by timmccabe** [comment]
I got it to run by adding these to the Proxy (Thread) class:

public InputStream clientIn;
public OutputStream clientOut;
public InputStream serverIn;
public OutputStream serverOut;

And by importing this:

import java.io.InterruptedIOException;

Now it runs but it seems to stop all web browsing. It is not clear to me if the proxy is actually configured, or if I must make it myself, how to let some traffic through, how to prevent other traffic, etc? Can I view more than just URLs? Can I view, for example, the content of a webpage inside the proxy code before allowing it through?

**Comment by DrBrad** [comment]
This just converts all traffic into a socket in which you can handle everything from their. If you want to route it traffic through a SOCKS proxy I recommend using my other project.
https://github.com/DrBrad/JTun2Socks

I forgot to implement the methods you wrote. I just added them thank you!
