### ISSUE TITLE
Problem on android 11 

### ISSUE THREAD

**Issue by ubeyid** [DrBrad/Android-VPN-to-Socket#2]
It doesn't work on android 11 it makes internet connection so slow when I activate exception and look in android studio logs it always says read socket timeout exception!!

**Comment by DrBrad** [comment]
Do you mind expanding a little bit. This is android to socket you define where the socket leads.

**Comment by DrBrad** [comment]
[Proxy.java](https://github.com/DrBrad/Android-VPN-to-Socket/blob/master/app/src/main/java/vpntosocket/shadowrouter/org/vpntosocket/VPN/Proxy.java)

**Comment by ubeyid** [comment]
Problem is on Proxy.java class where you  read data from the server! It waits to read data from server for long time but it doesn't success and it throws SocketReadTimeoutException.

**Comment by ubeyid** [comment]
Your code is great and understandable 👏👏👏 .Is it possible that you have a problem with ip headers you didnt set cheksum and change the length of the data in ipheaders Or you think these fields are not important? I have no so much info about ip packets!!

**Comment by DrBrad** [comment]
It would surprise me if the issue pertained to any of the headers, however its possible. I would guess still that its somewhere in the proxy.java.

Would you be willing to post the error log?

**Comment by ubeyid** [comment]
When you route only one ip address .addRoute("194.163.43.216",32) and remove .addRoute("0.0.0.0",0)  it works perfectly. So I think  problem is  service.protect(server) in first thread it protect the server but in second and in the other thread server connection it cannot protect new server connections so problem begins here it waits for long time to connect server and then it throws SocketReadTimeOutException !!!

**Comment by DrBrad** [comment]
Maybe we need to protect after the connect on Proxy.java?

**Comment by DrBrad** [comment]
That or it may be an issue with bad passing of the intent?

**Comment by ubeyid** [comment]
Try to protect serverSocket in the below part not the server in multiple thread!!! I will try it tomorrow!

Socket socket;
            ServerSocket serverSocket = new ServerSocket(port);
            port = (short) (serverSocket.getLocalPort() & 0xFFFF);
            Log.e("info", "VPNtoSocket VPN started on port: "+serverSocket.getLocalPort());

**Comment by ubeyid** [comment]
İ made some modification on [Proxy.java](https://github.com/ubeyid/Android-VpnSocket-VpnProxy/blob/master/app/app/src/main/java/vpntosocket/shadowrouter/org/vpntosocket/VPN/Proxy.java) and [VPNService.java](https://github.com/ubeyid/Android-VpnSocket-VpnProxy/blob/master/app/app/src/main/java/vpntosocket/shadowrouter/org/vpntosocket/VPN/VPNService.java) and [NatSession.java](https://github.com/ubeyid/Android-VpnSocket-VpnProxy/blob/master/app/app/src/main/java/vpntosocket/shadowrouter/org/vpntosocket/VPN/NatSessionManager.java) and a little bit more on the remaining code and now it works perfectly !!! Project links is https://github.com/ubeyid/Android-VpnSocket-VpnProxy
